name: build

# 触发条件：在 push或合并请求 到 master 或 release开头的分支后
on:
  push:
    branches:
      - main
      - alpha
      - beta
  pull_request:
    branches: '*'

# 任务
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      # 执行测试和打包操作
      - name: Install deps
        run: npm ci

      - name: Release
        run: npm run release --workspace @alova/scene-vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ALOVA_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
